# Generated by Django 3.2.8 on 2022-01-08 08:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='1.jpg', upload_to=''),
        ),
    ]
